export const SINGAPORE_MASK = [
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                             xxx                                                                                                                        ",
    "                                                                            xx        xxxx                                                                                                              ",
    "                                                                           xxx      xxxxxx x        x                                                                                                   ",
    "                                                                          xxxxxxxx xxxxxxxxxxx                                                                                                          ",
    "                                                                           xxxxxx  xxxxxxxxxxxx        x                                                                                                ",
    "                                                                          xxx    xxxxxxxxxxxx                                                                                                           ",
    "                                                                         xxx xxxxxxxxxxxxxxx                                                                                                            ",
    "                                                                        xxxxxxxxxxxxxxxxxxxxx                                                                                                           ",
    "                                                                        xxxxxxxxxxxxxxxxxxxxx                                                                                                           ",
    "                                                                         xxxxxxxxxxxxxxxxxxx                          xxxxx                                                                             ",
    "                                                                        xxxxxxxxxxxxxxxxxx                          xxxxxxxx                                                                            ",
    "                                                                        xxxxxxxxxxxxxxxxxx                          xxxxxxxxx                                                                           ",
    "                                                                       xxxxxxxxxxxxxxxxx                           xxxxxxxxxx                                                                           ",
    "                                                                       xxxxxxxxxxxxxxxxx                            xxxxxxxxx                                                                           ",
    "                                                                       xxxxxxxxxxxxxxxxx                            xxxxxxxxx                                                                           ",
    "                                                                      xxxxxxxxxxxxxxxx                            xxxxxxxxxx                                                                            ",
    "                                                                      xxxxxxxxxxxxxxxx                           xxxxxxxxxxx                                                                            ",
    "                                                                     xxxxxxxxxxxxxxxxx                          xxxxxxxxxxxxx                                                                           ",
    "                                                                    xxxxxxxxxxxxxxxxxx                          xxxxxxxxxxxxx                                                                           ",
    "                                                                   xxxxxxxxxxxxxxxxxxxx                         xxxxxxxxxxxxx                                                                           ",
    "                                                                   xxxxxxxxxxxxxxxxxxxx                         xxxxxxxxxxxx                                                                            ",
    "                                                                  xxxxxxxxxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxx                                                                            ",
    "                                                                 xxxxxxxxxxxxxxxxxxxxxxxxx           x xx  xxxxxxxxxxxxxxx                                                                              ",
    "                                                                 xxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxx                                                                              ",
    "                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxx                                                                               ",
    "                                                                 xxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxx                                                                                  ",
    "                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx                                                                                 ",
    "                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                                                                                  ",
    "                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx   xx                                                                             ",
    "                                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                            ",
    "                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxx                                                                             ",
    "                                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxx                                                                               ",
    "                                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                ",
    "                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                    ",
    "                                                               xxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxx                                                                                                      ",
    "                                                               xxxxxxxxxxxxxxxxxxxx   xxxxxxxxx                                                                                                         ",
    "                                                               xxxxxxxxxxxxxxxxxxx xxxxxxxxx                                                                                                            ",
    "                                                               xxxxxxxxxxxxxxxxxxxx xxxxxxx                                                                                                             ",
    "                                                                xxxxxxxxxxxxxxxx    xxxx                                                                                                                ",
    "                                                                xxxxxxxxxxxxxxxx x   xx                                                                                                                 ",
    "                                                                   xxxxxxxxxxx xxx                                                                                                                      ",
    "                                                                 xxxxxxxxxxxxxxxxx                                                                                                                      ",
    "                                                                xxxxxxxxxxxxxxx                                                                                                                         ",
    "                                                                xxxxxxxxxxx  x                                                                                                                          ",
    "                                                                 xxxxx   xxx                                                                                                                            ",
    "                                                                  x       x                                                                                                                             ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        ",
    "                                                                             xx                                                                                                                         ",
    "                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                        "
];

export const MASK_WIDTH = SINGAPORE_MASK[0].length;
export const MASK_HEIGHT = SINGAPORE_MASK.length;
